### ISSUE TITLE
Error: Launch template not found, launch configuration is not supportedFeature request: TITLE

### ISSUE THREAD

**Issue by bs258q** [clowdhaus/eksup#53]
### Use case

checking to see if there is workaround for it, as analyze stops going further.

### Solution/User Experience

Please skip the ASG check

**Comment by bs258q** [comment]
Error: Launch template not found, launch configuration is not supported is the issue
how to go past that ?

**Comment by bryantbiggs** [comment]
unfortunately launch configurations are not supported, and I don't know that it would make sense to skip over those checks that are done on the launch template. any reason you are not making the switch to launch templates?

https://github.com/clowdhaus/eksup/blob/4957e8966caa8baf931d4d87860fbd6b348bad13/eksup/src/eks/checks.rs#L528-L530

**Comment by bryantbiggs** [comment]
closing this out since launch configuration is not planned to be supported here
