### ISSUE TITLE
How to use aws config credentials ;multi aws account how to switch with --profile

### ISSUE THREAD

**Issue by chaoxiaodi** [clowdhaus/eksup#58]
### Expected Behaviour

How to use aws config credentials ;multi aws account how to switch with --profile

### Current Behaviour

eksup analyze -r us-west-2 -c cluster-name

### Code snippet

```sh
ERROR eksup::eks::resources: Cluster k8s-devops not found
```

### Steps to Reproduce

How to use aws config credentials ;multi aws account how to switch with --profile

### eksup version

latest

### Operating system

macOS x86_64

**Comment by nanthinimuniapan** [comment]
Facing the same issue in aws multiaccount

**Comment by bryantbiggs** [comment]
`--profile` is supported in https://github.com/clowdhaus/eksup/releases/tag/v0.8.0
