### ISSUE TITLE
Feature: Allow specifying which kubeconfig file to use

### ISSUE THREAD

**Issue by NerdySoftPaw** [clowdhaus/eksup#63]
### Expected Behaviour

Able to connect to the cluster

### Current Behaviour

Error: Unable to connect to cluster. Ensure kubeconfig file is present and updated to connect to the cluster.

### Code snippet

```sh
AWS_PROFILE=pace-dev eksup analyze --output analysis.txt --cluster dev --region eu-central-1
```

### Steps to Reproduce

run AWS_PROFILE=pace-dev eksup analyze --output analysis.txt --cluster dev --region eu-central-1

while the Profile is configured to assume a role.

normal kubectl commands are working

### eksup version

0.9.0

### Operating system

macOS x86_64

### Error output

```Text
Verbose logs are available can be provided via PN. because of Some Confidential Data

Error output without verbose logs is:

Error: Unable to connect to cluster. Ensure kubeconfig file is present and updated to connect to the cluster.
      Try: aws eks update-kubeconfig --name dev
```

**Comment by NerdySoftPaw** [comment]
I could fix this issue, with merging all my kubeconfigs into 1 and then save it as .kube/config file. after this eksup was able to read the config and find the cluster.

It would be great if there will be an parameter to add a custom kubeconfig file.

**Comment by bryantbiggs** [comment]
isn't that the norm though, one config file but with various contexts?
